name: Playcen - SkyPvP
version: 0.1
main: eu.playcen.skypvp.main.Main

commands:
   gamemode:
      aliases: gm
   fly:
   vanish:
   heal:
   tp:
   tphere:
   tppos:
   giveall:
   chatclear:
      aliases: cc
   kit:
      aliases: kits