name: SkyPvP
version: 0.6
main: eu.playcen.skypvp.main.Main

commands:
   gamemode:
      aliases: gm
   fly:
      description: Setze dich oder Andere in den Flugmodus
   vanish:
      aliases: v
   heal:
      description: Heilt dich oder andere Spieler komplett
   tp:
   tphere:
   tppos:
   giveall:
   chatclear:
      aliases: cc
   kit:
      aliases: kits
   sun:
   craft:
   globalmute:
      aliases: gmute
   setspawn:
   itemlist:
   teamspeak:
      aliases: ts
   discord:
      aliases: dc
   perks:
   cvillager:
   clear:
   ec:
      aliases: enderchest