name: SkyPvP
version: 0.1
main: eu.playcen.skypvp.main.Main

commands:
   gamemode:
      aliases: gm
   fly:
   vanish:
      aliases: v
   heal:
   tp:
   tphere:
   tppos:
   giveall:
   chatclear:
      aliases: cc
   kit:
      aliases: kits
   sun:
   craft:
   globalmute:
      aliases: gmute
   setspawn: