name: SkyPvP
version: 0.8
main: eu.playcen.skypvp.main.Main
depend: [CoinsAPI]

commands:
   gamemode:
      aliases: gm
   fly:
      description: Setze dich oder Andere in den Flugmodus
   vanish:
      aliases: v
   heal:
      description: Heilt dich oder andere Spieler komplett
   tp:
   tphere:
   tppos:
   giveall:
   chatclear:
      aliases: cc
   kit:
      aliases: kits
   sun:
   craft:
   globalmute:
      aliases: gmute
   setspawn:
   teamspeak:
      aliases: ts
   discord:
      aliases: dc
   perks:
   cvillager:
   clear:
   ec:
      aliases: enderchest
   invsee:
   clearlag:
   ping:
   rename:
   anvil:
      aliases: amboss
   enchanter:
   sign:
   skin:
   stats:
   statsreset:
   build:
   broadcast:
      aliases: bc
   msg:
   respond:
      aliases: r
   msgtoggle:
   setpvphöhe: